export const barChartStyles = {
    chartCard: {
        width: "100%",
        maxWidth: "100%",
        alignSelf: "center",
        backgroundColor: "background.paper",
        borderRadius: 3,
        boxShadow: "0 8px 18px rgba(0, 0, 0, 0.08)",
        p: 2,
        position: "relative",
    },
    chartTopUnit: {
        textAlign: "center",
        fontSize: "0.75rem",
        color: "text.secondary",
        mb: 1,
        textTransform: "lowercase",
    },
    chartArea: {
        width: "100%",
        minHeight: 260,
        display: "flex",
        alignItems: "flex-end",
        gap: 0.75,
        borderBottom: "1px solid",
        borderColor: "divider",
        pb: 1,
        position: "relative",
        overflowX: "auto",
    },
    gridLayer: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        pointerEvents: "none",
        zIndex: 0,
    },
    gridLine: {
        position: "absolute",
        left: 0,
        right: 0,
        borderTop: "1px dashed",
        borderColor: "divider",
    },
    barItem: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 0.5,
        zIndex: 1,
    },
    barValue: {
        fontSize: "0.7rem",
        color: "text.secondary",
        fontWeight: 700,
        whiteSpace: "nowrap",
    },
    barTrack: {
        width: "100%",
        height: 180,
        display: "flex",
        alignItems: "flex-end",
        gap: 0.35,
    },
    barFill: {
        width: "100%",
        borderRadius: "6px 6px 2px 2px",
    },
    barLabel: {
        fontSize: "0.7rem",
        color: "text.secondary",
        textAlign: "center",
        width: "100%",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    chartBottomUnit: {
        textAlign: "center",
        fontSize: "0.75rem",
        color: "text.secondary",
        mt: 1,
        textTransform: "lowercase",
    },
    legendBox: {
        position: "absolute",
        top: 8,
        right: 8,
        border: "1px solid",
        borderColor: "divider",
        borderRadius: 1.5,
        px: 1,
        py: 0.75,
        backgroundColor: "background.paper",
        display: "flex",
        flexDirection: "column",
        gap: 0.5,
        zIndex: 2,
        minWidth: 104,
    },
    legendItem: {
        display: "flex",
        alignItems: "center",
        gap: 0.6,
    },
    legendSwatch: {
        width: 10,
        height: 10,
        borderRadius: 0.5,
        flexShrink: 0,
    },
    legendLabel: {
        fontSize: "0.68rem",
        color: "text.secondary",
        lineHeight: 1,
    },
};
