export const dairyBarChartStyles = {
    page: {
        display: "flex",
        flexDirection: "column",
        flex: 1,
        minHeight: "100%",
        pb: 3,
        gap: 2,
    },
    rangeText: {
        textAlign: "center",
        fontWeight: 600,
        color: "text.primary",
    },
    averagesCard: {
        width: "100%",
        maxWidth: 560,
        alignSelf: "center",
        display: "grid",
        gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" },
        gap: 1.5,
        p: 2,
        borderRadius: 3,
        backgroundColor: "background.paper",
        boxShadow: "0 8px 18px rgba(0, 0, 0, 0.08)",
    },
    averageItem: {
        display: "flex",
        flexDirection: "column",
        gap: 0.5,
        p: 1,
        borderRadius: 2,
        border: "1px solid",
        borderColor: "divider",
    },
    averageLabel: {
        fontSize: "0.8rem",
        color: "text.secondary",
        fontWeight: 600,
    },
    averageValue: {
        fontSize: "1.5rem",
        lineHeight: 1,
        color: "text.primary",
        fontWeight: 700,
    },
    bottomActions: {
        width: "100%",
        maxWidth: 560,
        alignSelf: "center",
        display: "flex",
        gap: 2,
        mt: "auto",
    },
};
