export const resultScalesStyles = {
    page: {
        mt: 2,
        display: "flex",
        flexDirection: "column",
        flex: 1,
        minHeight: "100%",
        pb: 3,
    },
    rowsContainer: {
        width: "100%",
        maxWidth: 560,
        alignSelf: "center",
        display: "flex",
        flexDirection: "column",
        gap: 2,
        pt: 1,
    },
    row: {
        width: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 2,
        p: 1,
        borderRadius: 2,
        borderColor: "divider",
        backgroundColor: "background.paper",
    },
    rowDivider: {
        borderColor: "divider",
        opacity: 0.8,
        my: 0.5,
    },
    aspectColumn: {
        width: 86,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 0.75,
    },
    aspectButton: (hasRoute) => ({
        width: 72,
        height: 72,
        borderRadius: "50%",
        border: "2.5px solid #1a8090",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: hasRoute ? "pointer" : "default",
        "&:hover": {
            backgroundColor: hasRoute ? "rgba(26, 128, 144, 0.08)" : "transparent",
        },
    }),
    aspectIcon: {
        width: 40,
        height: 40,
        objectFit: "contain",
    },
    aspectLabel: {
        maxWidth: 84,
        lineHeight: 1.25,
        fontSize: 12,
        color: "text.primary",
        textAlign: "center",
    },
    ratingContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 1,
        flex: 1,
        pr: 1,
    },
    ratingIcon: {
        width: 40,
        height: 40,
        objectFit: "contain",
    },
    bottomActions: {
        mt: "auto",
        width: "100%",
        maxWidth: 560,
        alignSelf: "center",
        pt: 4,
    },
};
