import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { 
    Typography, 
    Button, 
    Box,
    TextField,
    Grid
} from "@mui/material";
import { useTranslation } from 'react-i18next';
import ViewContainer from "../components/ViewContainer";
import { 
    messageStyle, 
    errorBlockStyle, 
    imageStyle,
    buttonContainerStyle 
} from "../theme/Error.styles";
import { generateErrorReportImage } from "../utils/errorReport";
import image from "../assets/error_boundary_h.jpeg";


const Error = ({error, errorInfo, onReset}) => {

    const { t } = useTranslation();
    const navigate = useNavigate();
    const reportRef = useRef(null);
    const [isReporting, setIsReporting] = useState(false);

    const errorName = error?.name || "Error";
    const errorMessage = error?.message || String(error || "Unknown error");
    const errorStack = error?.stack || "No stack trace available";
    const componentStack = errorInfo?.componentStack || "No component stack available";

    const timestamp = new Date().toISOString();

    const crashDump = [
        `${errorName}: ${errorMessage}`,
        "",
        "Stack trace:",
        errorStack,
        "",
        "Component stack:",
        componentStack,
        "",
        `Timestamp: ${timestamp}`,
        `URL: ${window.location.href}`,
        `User agent: ${navigator.userAgent}`,
        `Viewport: ${window.innerWidth}x${window.innerHeight}`,
        `Device pixel ratio: ${window.devicePixelRatio}`,
    ].join("\n");


    const handleReport = async () => {
        if (isReporting) {
            return;
        }

        try {
            setIsReporting(true);

            const file = await generateErrorReportImage(
                reportRef.current
            );

            if (
                navigator.share &&
                navigator.canShare &&
                navigator.canShare({ files: [file] })
            ) {
                await navigator.share({
                    title: "Application error report",
                    text: "Error report generated by the application.",
                    files: [file],
                });

                return;
            }

            // Fallback for browsers without file sharing.
            const url = URL.createObjectURL(file);
            const link = document.createElement("a");

            link.href = url;
            link.download = file.name;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            URL.revokeObjectURL(url);
        } catch (error) {
            // AbortError means the user closed the share dialog.
            if (error?.name !== "AbortError") {
                console.error("Could not generate error report:", error);
            }
        } finally {
            setIsReporting(false);
        }
    };

    const handleReset = () => {
        onReset();
        navigate("/home");
    };

    return(
        <ViewContainer
            onBack={null}
            title={t("error.title")}
            headerSx={{background: "linear-gradient(to right, #ff0000, #0000ff)"}}>
            
            <Box ref={reportRef}>
                <Typography sx={messageStyle} mb={2}>
                    {t("error.message1")}
                </Typography>

                <img
                    src={image}
                    style={imageStyle}
                    alt=""/>

                <Typography sx={messageStyle}>
                    {t("error.message2")}
                </Typography>

                <Grid
                    sx={buttonContainerStyle }
                    container
                    direction="row"
                    justifyContent="space-evenly">
                    <Grid item>
                        <Button
                            onClick={handleReport}
                            variant="contained"
                            color="primary"
                            disabled={isReporting}>
                            {isReporting
                                ? "Generating..."
                                : t("error.sendReport")}
                        </Button>
                    </Grid>

                    <Grid item>
                        <Button
                            onClick={handleReset}
                            variant="contained"
                            color="primary">
                            {t("error.reset")}
                        </Button>
                    </Grid>
                </Grid>

                <Box
                    sx={errorBlockStyle}>
                    <Typography
                        sx={{
                            fontFamily: "monospace",
                            fontSize: "13px",
                            lineHeight: 1.5,
                            color: "#ff0000",
                            whiteSpace: "pre-wrap",
                            overflowWrap: "break-word",
                            wordBreak: "break-word",
                        }}>
                        {crashDump}
                    </Typography>
                </Box>
            </Box>
        </ViewContainer>
    );
};

export default Error;